add support link
azimuth-cloud/ansible-collection-azimuth-ops pull request #609
Opened 2024-08-29 13:15 UTC by thinkC

2024-09-19 11:06 UTC, mkjpryor requested changes

2024-09-19 11:06 UTC, mkjpryor commented on roles/azimuth/defaults/main.yml
> +azimuth_support_url: https://confluence.skatelescope.org/display/SRCSC/Azimuth+Support+on+Cambridge+Arcus
Similar to the Azimuth PR, this should not have a value by default.

2024-11-06 10:02 UTC, thinkC commented
Hello @mkjpryor, I changes made . Kindly review

2024-11-06 10:15 UTC, JohnGarbutt reviewed
This looks worth adding.

We might also want to tweak to the docs so it's clear this is an option? Maybe that is overkill. I will let @mkjpryor re-review this one.

2024-11-12 12:17 UTC, JohnGarbutt commented on roles/azimuth/defaults/main.yml
> +azimuth_support_url: None
ah, doh, I missed that, good point.

2024-11-12 16:36 UTC, thinkC commented on roles/azimuth/defaults/main.yml
> +azimuth_support_url: None
Thanks @mkjpryor . Updated

2024-11-25 14:54 UTC, mkjpryor approved these changes
LGTM

2024-11-25 14:54 UTC, merged